name: Deploy to S3

on:
  push:
    branches:
      - main
    paths:
        - 'src/**'
        - 'public/**'
        - 'package.json'
        - 'package-lock.json'
        - '/.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.DEPLOY_ACTIONS_ROLE }}
          aws-region: ap-northeast-1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build frontend app
        run: npm run build

      - name: Sync /out directory to S3
        run: aws s3 sync ./out s3://portfolio-spa-static --exact-timestamps
